[package]
name = "wordl"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.4"
http = "1.1.0"
rand = "0.8.5"
shuttle-axum = "0.45.0"
shuttle-runtime = "0.45.0"
tower-http = { version = "0.5.2", features = ["fs", "cors"] }
tracing = "0.1.40"


[workspace]
members = [".", "frontend"]
